### ISSUE TITLE
Cannot use self-hosted models

### ISSUE THREAD

**Issue by seungduk-yanolja** [yanolja/ogem#22]
Should support something as follows:
```
providers:
  mine:
    endpoint:
    protocol:
    api_key_env:
    regions:
      mine:
        models:
```
